#!/bin/bash

# BatchResolve v1.0 (11/1/2018)
# ©2018 James Mariano
# This script uses nslookup to determine the FQDNs from a list of IP addresses.
# ----------------------------------------------------------------------------------------------
# Future development is to include:
# 1) The ability to pass a range of IPs through CIDR notation (e.g. batchresolve 192.168.0.0/16) 
#    or defined range (e.g. batchresolve 192.168.0.4-12)
# 2) An option to save the output to a file.

#ARGUMENT OPTIONS
while getopts ":i:" opt; do
	case ${opt} in
	#Input File
	i ) IN_FILE=$OPTARG
		if [ ! -e $OPTARG ]; then
			echo "File does not exist. Try again."
			exit 1
		elif [ ! -f $OPTARG ]; then
			echo "$OPTARG is not a file. Try again."
			exit 1
		else
			while read i; do
				RETURN_IP="$(nslookup $i | grep name | cut -d "=" -f2)"
				if [ -n "$RETURN_IP" ]; then
					echo $i "=" ${RETURN_IP::-1}
				fi;
			done < "$IN_FILE";
		fi;;
	esac
done
shift $((OPTIND -1))

